apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: audit-tool-git-sha256-1
        image: gcr.io/audit-tool-285315/audit-tool-git
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-1
  name: audit-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/audit-service
spec:
  ports:
  - nodePort: 31100
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: nginx-1
  type: LoadBalancer