apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: audit-site
        image: ibasak/audittoolassignment:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: audit-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
